// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngjtckzeusrhdegwbnrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nanRja3pldXNyaGRlZ3dibnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTU5NzksImV4cCI6MjA2ODQ3MTk3OX0.JrOaNSQUd3RqMhFKiO5QsL21PvSo7DzhYEFST6ZUdtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});